---
# tasks file for php-file-update


- name: Updatinging php.ini file
  lineinfile:
    path: /etc/php/7.2/apache2/php.ini
    regexp: '^file_uploads'
    line: file_uploads = {{ file_uploads_value }}
                            
                            
- name: Updatinging allow_url_fopen php.ini file
  lineinfile:
    path: /etc/php/7.2/apache2/php.ini
    regexp: '^allow_url_fopen'
    line: allow_url_fopen = {{ allow_url_fopen_value }}

- name: Updatinging short_open_tag php.ini file
  lineinfile:
    path: /etc/php/7.2/apache2/php.ini
    regexp: '^short_open_tag'
    line: short_open_tag = {{ short_open_tag_value }}
                            
- name: Updatinging memory_limit php.ini file
  lineinfile:
    path: /etc/php/7.2/apache2/php.ini
    regexp: '^memory_limit'
    line: memory_limit = {{ memory_limit_value }}
                            
- name: Updatinging upload_max_filesize php.ini file
  lineinfile:
    path: /etc/php/7.2/apache2/php.ini
    regexp: '^upload_max_filesize'
    line: upload_max_filesize = {{ upload_max_filesize_value }}
                            
- name: Updatinging max_execution_time php.ini file
  lineinfile:
    path: /etc/php/7.2/apache2/php.ini
    regexp: '^max_execution_time'
    line: max_execution_time = {{ max_execution_time_value }}

- name: Updating Mysql conf file
  lineinfile:
    path: /etc/php/7.2/apache2/php.ini
    regexp: '^bind-address'
    line: bind-address = 0.0.0.0
