---
# tasks file for php

- name: Installing Php repository
  apt: 
        name: 
              - php7.2
              - libapache2-mod-php7.2
              - php7.2-common
              - php7.2-gmp
              - php7.2-curl
              - php7.2-soap
              - php7.2-bcmath
              - php7.2-intl
              - php7.2-mbstring
              - php7.2-xmlrpc
              - php7.2-mysql
              - php7.2-gd
              - php7.2-xml
              - php7.2-cli
              - php7.2-zip
              - unzip
              - libmcrypt-dev
              - libreadline-dev
              - php-pear
              - php7.2-dev
        
        state: latest

- name: Installing pecl
  shell: >
     pecl channel-update pecl.php.net

- name: Updating pecl
  shell: >
     echo -ne '\n' | sudo pecl install mcrypt-1.0.1 

